### PR TITLE
GenericIPAddressField for wordpress.Comment.author_ip

### PR DESCRIPTION
**Pull request by vanwarantion**
IPAddressField has been removed except for support in historical migrations.

### CODE REVIEW

**Comment by kopf** [comment]
Ping @jcarbaugh - any idea when this will be merged and released? 

This is the last hurdle I have in migrating a large application from django 1.7 to 1.11. It would be therefore be great to see this in `master` as soon as possible :)

**Comment by jcarbaugh** [comment]
@kopf hello! I've been hesitant to push out a release because I haven't had the time to verify that this package still works with the current versions of WordPress and Django. I'll merge this now, but would you be able to verify that master works for your use case before I push a new release?

**Comment by jcarbaugh** [comment]
@vanwarantion a very belated thank you for the contribution!

**Comment by kopf** [comment]
Hey @jcarbaugh, thanks for merging. 

I had forked from this branch and installed directly from the repo, and I can confirm that it works fine. Can query on and set the `Comment.author_ip` without problems.

**Comment by jcarbaugh** [comment]
@kopf thanks for checking on that! I just pushed 0.11 to PyPI https://pypi.org/project/the-real-django-wordpress/

**Pull request merged**
